some small refactoring
MusicConnectionMachine/Relationships pull request #70
Opened 2017-04-22 15:25 UTC by simonzachau

2017-04-22 16:13 UTC, Henni requested changes

2017-04-22 16:13 UTC, Henni commented on app/algorithms/index.js
> +        return Promise.reject(new Error('no resultArr[0].text'));
`throw` an error instead of creating a new Promise here.

2017-04-23 11:09 UTC, simonzachau commented
@Henni update your review status please

2017-04-23 11:59 UTC, Henni approved these changes

2017-04-23 12:13 UTC, merged