Relationship not getting store fix
MusicConnectionMachine/Relationships pull request #79
Opened 2017-05-04 10:47 UTC by ansjin

2017-05-04 14:38 UTC, Sandr00 commented on app/dbConnection/index.js
>                return artist.setEntity(newEntity).then(() => newEntity);
Maybe we should NOT set that here? @ansjin what do you think?

2017-05-04 14:41 UTC, Sandr00 commented on app/dbConnection/index.js
> +    return artists.find({
Reason for null-artists, Before merging, please check this case as well!

2017-05-04 14:56 UTC, Henni requested changes

2017-05-04 14:56 UTC, Henni commented on app/dbConnection/index.js
> +        'SELECT * from (SELECT blob_url, COUNT(*) as count FROM (select * from websites limit 100000 ) w LEFT JOIN contains c ON w.id = c."websiteId" GROUP BY blob_url ORDER BY count DESC) a where a.
* [ ] remove limit
* [ ] make threshold configurable and pass it into the query

2017-05-04 15:05 UTC, Sandr00 commented on app/dbConnection/index.js
> +              'artist_type': 'Composer'
Entity has no artist type, but artist has.

2017-05-04 15:20 UTC, Sandr0x00 requested changes

2017-05-04 15:20 UTC, Sandr00 commented on app/dbConnection/index.js
>  exports.writeEvents = function (eventEntityJSON) {
@ansjin I do not understand this method, can you check that again please?
Problems:
- The stuff i wrote in other comments
- In the last then, we collect all promises, but then ignore them?
- We should create a event, even if we have no corresponding artist or entity.
- We should not create artists!
- We should not create entities? Or should we? Makes no sense in my Opinion.

I think the best way would be to create `relationshipEntities`. Maybe.

We should check if `entityName` is `undefined` or `null`, before creating null-entries ;)
Where do we get the `entityName`? Does the algorithm already know the entity?

2017-05-05 11:04 UTC, Sandr0x00 approved these changes

2017-05-05 16:17 UTC, ansjin commented
no merging until we test this!

2017-06-02 22:37 UTC, kordianbruck commented
@anshul0708 @Sandr00 can we get this merged please, so we have it for our run?

2017-06-03 06:34 UTC, ansjin commented
@kordianbruck  you tagged here the other anshul :)

2017-06-03 06:37 UTC, ansjin commented
@Henni Please approve this!

2017-06-04 11:04 UTC, Henni approved these changes

2017-06-04 15:26 UTC, merged

2017-06-06 08:25 UTC, kordianbruck commented
@ansjin happens to me every time :cry: