WIP: Azure Queues
MusicConnectionMachine/Relationships pull request #80
Opened 2017-05-04 10:48 UTC by Henni

use Azure's ServiceBusService to pass messages.

2017-05-04 11:04 UTC, pfent approved these changes
Seems fine.

2017-05-04 11:06 UTC, Sandr0x00 submitted a review, later dismissed
This should not yet be merged ;)

2017-05-04 11:06 UTC, ansjin commented
This should not be merged

2017-05-05 21:00 UTC, simonzachau commented on app/config.js
> +    'namespace': 'relationshipns',
should it be ```relationships```?

2017-05-05 21:01 UTC, ansjin commented on app/config.js
> +    'namespace': 'relationshipns',
nope, its relationshipns only (ns for namespace)

2017-05-05 21:02 UTC, ansjin requested changes
not to be merged. I am working on it

2017-05-06 11:21 UTC, ansjin commented
Now this can be merged.

2017-05-06 11:21 UTC, ansjin approved these changes

2017-06-02 22:34 UTC, merged

2017-06-02 22:35 UTC, kordianbruck commented
@anshul0708 we need your to finish this! Please respond in Gitter!

2017-06-03 07:21 UTC, Sandr00 commented
@kordianbruck Wrong Anshul, we got the **Jindal** not the **Sharma** 😅

2017-06-06 08:24 UTC, kordianbruck commented
@Sandr00 wups :disappointed: